In [1]:
import numpy as np
import random
from random import randint, choice

# Solution

In [60]:
initial_matrix = np.zeros((8,8))

In [68]:
list_row = [i for i in range(8)]
list_col = [i for i in range(8)]
row_index_1 = 0
col_index_1 = 0
a = True
for i in range(8):
    print(i)
    initial_matrix = np.zeros((8,8))
    step_1_matrix = initial_matrix
    step_1_matrix[row_index_1,col_index_1] = 1
    print('Step 1 Matrix:')
    print(step_1_matrix)
    print("---------------------------------------------------")
    a = True
    while a == True:
        row_index_2 = random.randint(0,7)
        col_index_2 = random.randint(0,7)
        if np.sum(np.equal(np.array([row_index_2,col_index_2,row_index_2+col_index_2,row_index_2-col_index_2]), np.array([row_index_1,col_index_1,row_index_1+col_index_1,row_index_1-col_index_1]))) == 0:
            a=False
    step_2_matrix = step_1_matrix
    step_2_matrix[row_index_2,col_index_2] = 1
    print('Step 2 Matrix:')
    print(step_2_matrix)
    print("---------------------------------------------------")
    a = True
    while a == True:
        row_index_3 = random.randint(0,7)
        col_index_3 = random.randint(0,7)
        if np.sum(np.equal(np.array([row_index_3,col_index_3,row_index_3+col_index_3,row_index_3-col_index_3]), np.array([row_index_1,col_index_1,row_index_1+col_index_1,row_index_1-col_index_1]))) +  np.sum(np.equal(np.array([row_index_2,col_index_2,row_index_2+col_index_2,row_index_2-col_index_2]), np.array([row_index_3,col_index_3,row_index_3+col_index_3,row_index_3-col_index_3]))) == 0:
            a=False
    
    step_3_matrix = step_2_matrix
    step_3_matrix[row_index_3,col_index_3] = 1
    print('Step 3 Matrix:')
    print(step_3_matrix)
    print("---------------------------------------------------")
    a = True
    while a == True:
        row_index_4 = random.randint(0,7)
        col_index_4 = random.randint(0,7)
        if np.sum(np.equal(np.array([row_index_4,col_index_4,row_index_4+col_index_4,row_index_4-col_index_4]), np.array([row_index_1,col_index_1,row_index_1+col_index_1,row_index_1-col_index_1]))) + np.sum(np.equal(np.array([row_index_4,col_index_4,row_index_4+col_index_4,row_index_4-col_index_4]), np.array([row_index_3,col_index_3,row_index_3+col_index_3,row_index_3-col_index_3]))) + np.sum(np.equal(np.array([row_index_4,col_index_4,row_index_4+col_index_4,row_index_4-col_index_4]), np.array([row_index_2,col_index_2,row_index_2+col_index_2,row_index_2-col_index_2]))) == 0:
            a=False
            
    step_4_matrix = step_3_matrix
    step_4_matrix[row_index_4,col_index_4] = 1
    print('Step 4 Matrix:')
    print(step_4_matrix)
    print("---------------------------------------------------")
    a = True
    while a == True:
        row_index_5 = random.randint(0,7)
        col_index_5 = random.randint(0,7)
        if np.sum(np.equal(np.array([row_index_5,col_index_5,row_index_5+col_index_5,row_index_5-col_index_5]), np.array([row_index_1,col_index_1,row_index_1+col_index_1,row_index_1-col_index_1]))) + np.sum(np.equal(np.array([row_index_5,col_index_5,row_index_5+col_index_5,row_index_5-col_index_5]), np.array([row_index_3,col_index_3,row_index_3+col_index_3,row_index_3-col_index_3]))) + np.sum(np.equal(np.array([row_index_5,col_index_5,row_index_5+col_index_5,row_index_5-col_index_5]), np.array([row_index_4,col_index_4,row_index_4+col_index_4,row_index_4-col_index_4]))) + np.sum(np.equal(np.array([row_index_5,col_index_5,row_index_5+col_index_5,row_index_5-col_index_5]), np.array([row_index_2,col_index_2,row_index_2+col_index_2,row_index_2-col_index_2]))) == 0:
            a=False
    step_5_matrix = step_4_matrix
    step_5_matrix[row_index_5,col_index_5] = 1
    print('Step 5 Matrix:')
    print(step_5_matrix)
    print("---------------------------------------------------")
    
    row_list_6 = list(set(list_row) - set([row_index_1,row_index_2,row_index_3,row_index_4,row_index_5]))
    col_list_6 = list(set(list_col) - set([col_index_1,col_index_2,col_index_3,col_index_4,col_index_5]))
    
    for col_in in range(3):
        col_index_6 = col_list_6[col_in]
        for row_in in range(3):
            row_index_6 = row_list_6[row_in]
            if np.sum(np.equal(np.array([row_index_6,col_index_6,row_index_6+col_index_6,row_index_6-col_index_6]), np.array([row_index_1,col_index_1,row_index_1+col_index_1,row_index_1-col_index_1]))) + np.sum(np.equal(np.array([row_index_6,col_index_6,row_index_6+col_index_6,row_index_6-col_index_6]), np.array([row_index_3,col_index_3,row_index_3+col_index_3,row_index_3-col_index_3]))) + np.sum(np.equal(np.array([row_index_6,col_index_6,row_index_6+col_index_6,row_index_6-col_index_6]), np.array([row_index_4,col_index_4,row_index_4+col_index_4,row_index_4-col_index_4]))) + np.sum(np.equal(np.array([row_index_6,col_index_6,row_index_6+col_index_6,row_index_6-col_index_6]), np.array([row_index_2,col_index_2,row_index_2+col_index_2,row_index_2-col_index_2]))) + np.sum(np.equal(np.array([row_index_6,col_index_6,row_index_6+col_index_6,row_index_6-col_index_6]), np.array([row_index_5,col_index_5,row_index_5+col_index_5,row_index_5-col_index_5]))) == 0:
                break
        else:
            continue
        break
    
    

            
    step_6_matrix = step_5_matrix
    step_6_matrix[row_index_6,col_index_6] = 1
    print('Step 6 Matrix:')
    print(step_6_matrix)
    print("---------------------------------------------------")
    
    row_list_7 = list(set(list_row) - set([row_index_1,row_index_2,row_index_3,row_index_4,row_index_5,row_index_6]))
    col_list_7 = list(set(list_col) - set([col_index_1,col_index_2,col_index_3,col_index_4,col_index_5,row_index_6]))

    for col_in in range(2):
        col_index_7 = col_list_7[col_in]
        for row_in in range(2):
            row_index_7 = row_list_7[row_in]
            if np.sum(np.equal(np.array([row_index_7,col_index_7,row_index_7+col_index_7,row_index_7-col_index_7]), np.array([row_index_1,col_index_1,row_index_1+col_index_1,row_index_1-col_index_1]))) + np.sum(np.equal(np.array([row_index_7,col_index_7,row_index_7+col_index_7,row_index_7-col_index_7]), np.array([row_index_3,col_index_3,row_index_3+col_index_3,row_index_3-col_index_3]))) + np.sum(np.equal(np.array([row_index_7,col_index_7,row_index_7+col_index_7,row_index_7-col_index_7]), np.array([row_index_4,col_index_4,row_index_4+col_index_4,row_index_4-col_index_4]))) + np.sum(np.equal(np.array([row_index_7,col_index_7,row_index_7+col_index_7,row_index_7-col_index_7]), np.array([row_index_2,col_index_2,row_index_2+col_index_2,row_index_2-col_index_2]))) + np.sum(np.equal(np.array([row_index_7,col_index_7,row_index_7+col_index_7,row_index_7-col_index_7]), np.array([row_index_5,col_index_5,row_index_5+col_index_5,row_index_5-col_index_5]))) + np.sum(np.equal(np.array([row_index_7,col_index_7,row_index_7+col_index_7,row_index_7-col_index_7]), np.array([row_index_6,col_index_6,row_index_6+col_index_6,row_index_6-col_index_6]))) == 0:
                break
        else:
            continue
        break  

            
    step_7_matrix = step_6_matrix
    step_7_matrix[row_index_7,col_index_7] = 1
    print('Step 7 Matrix:')
    print(step_7_matrix)
    print("---------------------------------------------------")
    row_index_8 = list(set(list_row) - set([row_index_1,row_index_2,row_index_3,row_index_4,row_index_5,row_index_6,row_index_7]))[0]
    col_index_8 = list(set(list_col) - set([col_index_1,col_index_2,col_index_3,col_index_4,col_index_5,col_index_6,col_index_7]))[0] 
    if np.sum(np.equal(np.array([row_index_8,col_index_8,row_index_8+col_index_8,row_index_8-col_index_8]), np.array([row_index_1,col_index_1,row_index_1+col_index_1,row_index_1-col_index_1]))) + np.sum(np.equal(np.array([row_index_8,col_index_8,row_index_8+col_index_8,row_index_8-col_index_8]), np.array([row_index_3,col_index_3,row_index_3+col_index_3,row_index_3-col_index_3]))) + np.sum(np.equal(np.array([row_index_8,col_index_8,row_index_8+col_index_8,row_index_8-col_index_8]), np.array([row_index_4,col_index_4,row_index_4+col_index_4,row_index_4-col_index_4]))) + np.sum(np.equal(np.array([row_index_8,col_index_8,row_index_8+col_index_8,row_index_8-col_index_8]), np.array([row_index_2,col_index_2,row_index_2+col_index_2,row_index_2-col_index_2]))) + np.sum(np.equal(np.array([row_index_8,col_index_8,row_index_8+col_index_8,row_index_8-col_index_8]), np.array([row_index_5,col_index_5,row_index_5+col_index_5,row_index_5-col_index_5]))) + np.sum(np.equal(np.array([row_index_8,col_index_8,row_index_8+col_index_8,row_index_8-col_index_8]), np.array([row_index_6,col_index_6,row_index_6+col_index_6,row_index_6-col_index_6]))) + np.sum(np.equal(np.array([row_index_8,col_index_8,row_index_8+col_index_8,row_index_8-col_index_8]), np.array([row_index_7,col_index_7,row_index_7+col_index_7,row_index_7-col_index_7]))) == 0:
        step_8_matrix = step_7_matrix
        step_8_matrix[row_index_8,col_index_8] = 1
        print('Step 8 Matrix:')
        print(step_8_matrix)
        print("---------------------------------------------------")
        print('Eight Queen Problem Solved ! GIVE ME A FREE MEAL :)')
        print("---------------------------------------------------")
        break
    else:
        print('Bir daha deneniyor...')
        col_index_1 += 1

    

0
Step 1 Matrix:
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
---------------------------------------------------
Step 2 Matrix:
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
---------------------------------------------------
Step 3 Matrix:
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]
---------------------------------------------------
Step 4 Matrix:
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 